// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v5.29.3
// source: metadata.proto

package metadata

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RegisterUploadingObjectRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	TargetUserId    uint32                 `protobuf:"varint,1,opt,name=target_user_id,json=targetUserId,proto3" json:"target_user_id"`
	Bucket          string                 `protobuf:"bytes,2,opt,name=bucket,proto3" json:"bucket"`
	Key             string                 `protobuf:"bytes,3,opt,name=key,proto3" json:"key"`
	UploadTimestamp string                 `protobuf:"bytes,4,opt,name=upload_timestamp,json=uploadTimestamp,proto3" json:"upload_timestamp"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *RegisterUploadingObjectRequest) Reset() {
	*x = RegisterUploadingObjectRequest{}
	mi := &file_metadata_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterUploadingObjectRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterUploadingObjectRequest) ProtoMessage() {}

func (x *RegisterUploadingObjectRequest) ProtoReflect() protoreflect.Message {
	mi := &file_metadata_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterUploadingObjectRequest.ProtoReflect.Descriptor instead.
func (*RegisterUploadingObjectRequest) Descriptor() ([]byte, []int) {
	return file_metadata_proto_rawDescGZIP(), []int{0}
}

func (x *RegisterUploadingObjectRequest) GetTargetUserId() uint32 {
	if x != nil {
		return x.TargetUserId
	}
	return 0
}

func (x *RegisterUploadingObjectRequest) GetBucket() string {
	if x != nil {
		return x.Bucket
	}
	return ""
}

func (x *RegisterUploadingObjectRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *RegisterUploadingObjectRequest) GetUploadTimestamp() string {
	if x != nil {
		return x.UploadTimestamp
	}
	return ""
}

type RegisterUploadingObjectResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StatusCode    uint32                 `protobuf:"varint,1,opt,name=status_code,json=statusCode,proto3" json:"status_code"`
	StatusMsg     string                 `protobuf:"bytes,2,opt,name=status_msg,json=statusMsg,proto3" json:"status_msg"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterUploadingObjectResponse) Reset() {
	*x = RegisterUploadingObjectResponse{}
	mi := &file_metadata_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterUploadingObjectResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterUploadingObjectResponse) ProtoMessage() {}

func (x *RegisterUploadingObjectResponse) ProtoReflect() protoreflect.Message {
	mi := &file_metadata_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterUploadingObjectResponse.ProtoReflect.Descriptor instead.
func (*RegisterUploadingObjectResponse) Descriptor() ([]byte, []int) {
	return file_metadata_proto_rawDescGZIP(), []int{1}
}

func (x *RegisterUploadingObjectResponse) GetStatusCode() uint32 {
	if x != nil {
		return x.StatusCode
	}
	return 0
}

func (x *RegisterUploadingObjectResponse) GetStatusMsg() string {
	if x != nil {
		return x.StatusMsg
	}
	return ""
}

var File_metadata_proto protoreflect.FileDescriptor

const file_metadata_proto_rawDesc = "" +
	"\n" +
	"\x0emetadata.proto\x12\frpc.metadata\"\x9b\x01\n" +
	"\x1eRegisterUploadingObjectRequest\x12$\n" +
	"\x0etarget_user_id\x18\x01 \x01(\rR\ftargetUserId\x12\x16\n" +
	"\x06bucket\x18\x02 \x01(\tR\x06bucket\x12\x10\n" +
	"\x03key\x18\x03 \x01(\tR\x03key\x12)\n" +
	"\x10upload_timestamp\x18\x04 \x01(\tR\x0fuploadTimestamp\"a\n" +
	"\x1fRegisterUploadingObjectResponse\x12\x1f\n" +
	"\vstatus_code\x18\x01 \x01(\rR\n" +
	"statusCode\x12\x1d\n" +
	"\n" +
	"status_msg\x18\x02 \x01(\tR\tstatusMsg2\x89\x01\n" +
	"\x0fMetadataService\x12v\n" +
	"\x17RegisterUploadingObject\x12,.rpc.metadata.RegisterUploadingObjectRequest\x1a-.rpc.metadata.RegisterUploadingObjectResponseB\x1dZ\x1bQuickStone/src/rpc/metadatab\x06proto3"

var (
	file_metadata_proto_rawDescOnce sync.Once
	file_metadata_proto_rawDescData []byte
)

func file_metadata_proto_rawDescGZIP() []byte {
	file_metadata_proto_rawDescOnce.Do(func() {
		file_metadata_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_metadata_proto_rawDesc), len(file_metadata_proto_rawDesc)))
	})
	return file_metadata_proto_rawDescData
}

var file_metadata_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_metadata_proto_goTypes = []any{
	(*RegisterUploadingObjectRequest)(nil),  // 0: rpc.metadata.RegisterUploadingObjectRequest
	(*RegisterUploadingObjectResponse)(nil), // 1: rpc.metadata.RegisterUploadingObjectResponse
}
var file_metadata_proto_depIdxs = []int32{
	0, // 0: rpc.metadata.MetadataService.RegisterUploadingObject:input_type -> rpc.metadata.RegisterUploadingObjectRequest
	1, // 1: rpc.metadata.MetadataService.RegisterUploadingObject:output_type -> rpc.metadata.RegisterUploadingObjectResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_metadata_proto_init() }
func file_metadata_proto_init() {
	if File_metadata_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_metadata_proto_rawDesc), len(file_metadata_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_metadata_proto_goTypes,
		DependencyIndexes: file_metadata_proto_depIdxs,
		MessageInfos:      file_metadata_proto_msgTypes,
	}.Build()
	File_metadata_proto = out.File
	file_metadata_proto_goTypes = nil
	file_metadata_proto_depIdxs = nil
}
