// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v5.29.3
// source: bucket.proto

package bucket

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type StorageType int32

const (
	StorageType_STANDARD StorageType = 0
	StorageType_LOW_FREQ StorageType = 1
)

// Enum value maps for StorageType.
var (
	StorageType_name = map[int32]string{
		0: "STANDARD",
		1: "LOW_FREQ",
	}
	StorageType_value = map[string]int32{
		"STANDARD": 0,
		"LOW_FREQ": 1,
	}
)

func (x StorageType) Enum() *StorageType {
	p := new(StorageType)
	*p = x
	return p
}

func (x StorageType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (StorageType) Descriptor() protoreflect.EnumDescriptor {
	return file_bucket_proto_enumTypes[0].Descriptor()
}

func (StorageType) Type() protoreflect.EnumType {
	return &file_bucket_proto_enumTypes[0]
}

func (x StorageType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use StorageType.Descriptor instead.
func (StorageType) EnumDescriptor() ([]byte, []int) {
	return file_bucket_proto_rawDescGZIP(), []int{0}
}

type BucketACLType int32

const (
	BucketACLType_PRIVATE     BucketACLType = 0
	BucketACLType_PUBLIC_READ BucketACLType = 1
	BucketACLType_PUBLIC      BucketACLType = 2
)

// Enum value maps for BucketACLType.
var (
	BucketACLType_name = map[int32]string{
		0: "PRIVATE",
		1: "PUBLIC_READ",
		2: "PUBLIC",
	}
	BucketACLType_value = map[string]int32{
		"PRIVATE":     0,
		"PUBLIC_READ": 1,
		"PUBLIC":      2,
	}
)

func (x BucketACLType) Enum() *BucketACLType {
	p := new(BucketACLType)
	*p = x
	return p
}

func (x BucketACLType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (BucketACLType) Descriptor() protoreflect.EnumDescriptor {
	return file_bucket_proto_enumTypes[1].Descriptor()
}

func (BucketACLType) Type() protoreflect.EnumType {
	return &file_bucket_proto_enumTypes[1]
}

func (x BucketACLType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use BucketACLType.Descriptor instead.
func (BucketACLType) EnumDescriptor() ([]byte, []int) {
	return file_bucket_proto_rawDescGZIP(), []int{1}
}

type CreateBucketRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Bucket        string                 `protobuf:"bytes,1,opt,name=bucket,proto3" json:"bucket"`
	Area          string                 `protobuf:"bytes,2,opt,name=area,proto3" json:"area"` //桶的存储服务器所在地
	StorageType   StorageType            `protobuf:"varint,3,opt,name=storage_type,json=storageType,proto3,enum=rpc.bucket.StorageType" json:"storage_type"`
	AclType       BucketACLType          `protobuf:"varint,4,opt,name=acl_type,json=aclType,proto3,enum=rpc.bucket.BucketACLType" json:"acl_type"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateBucketRequest) Reset() {
	*x = CreateBucketRequest{}
	mi := &file_bucket_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateBucketRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateBucketRequest) ProtoMessage() {}

func (x *CreateBucketRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bucket_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateBucketRequest.ProtoReflect.Descriptor instead.
func (*CreateBucketRequest) Descriptor() ([]byte, []int) {
	return file_bucket_proto_rawDescGZIP(), []int{0}
}

func (x *CreateBucketRequest) GetBucket() string {
	if x != nil {
		return x.Bucket
	}
	return ""
}

func (x *CreateBucketRequest) GetArea() string {
	if x != nil {
		return x.Area
	}
	return ""
}

func (x *CreateBucketRequest) GetStorageType() StorageType {
	if x != nil {
		return x.StorageType
	}
	return StorageType_STANDARD
}

func (x *CreateBucketRequest) GetAclType() BucketACLType {
	if x != nil {
		return x.AclType
	}
	return BucketACLType_PRIVATE
}

type CreateBucketResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	StatusCode      uint32                 `protobuf:"varint,1,opt,name=status_code,json=statusCode,proto3" json:"status_code"`
	StatusMsg       string                 `protobuf:"bytes,2,opt,name=status_msg,json=statusMsg,proto3" json:"status_msg"`
	CreateTimestamp string                 `protobuf:"bytes,3,opt,name=create_timestamp,json=createTimestamp,proto3" json:"create_timestamp"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *CreateBucketResponse) Reset() {
	*x = CreateBucketResponse{}
	mi := &file_bucket_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateBucketResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateBucketResponse) ProtoMessage() {}

func (x *CreateBucketResponse) ProtoReflect() protoreflect.Message {
	mi := &file_bucket_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateBucketResponse.ProtoReflect.Descriptor instead.
func (*CreateBucketResponse) Descriptor() ([]byte, []int) {
	return file_bucket_proto_rawDescGZIP(), []int{1}
}

func (x *CreateBucketResponse) GetStatusCode() uint32 {
	if x != nil {
		return x.StatusCode
	}
	return 0
}

func (x *CreateBucketResponse) GetStatusMsg() string {
	if x != nil {
		return x.StatusMsg
	}
	return ""
}

func (x *CreateBucketResponse) GetCreateTimestamp() string {
	if x != nil {
		return x.CreateTimestamp
	}
	return ""
}

type DeleteBucketRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Bucket        string                 `protobuf:"bytes,1,opt,name=bucket,proto3" json:"bucket"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteBucketRequest) Reset() {
	*x = DeleteBucketRequest{}
	mi := &file_bucket_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteBucketRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteBucketRequest) ProtoMessage() {}

func (x *DeleteBucketRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bucket_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteBucketRequest.ProtoReflect.Descriptor instead.
func (*DeleteBucketRequest) Descriptor() ([]byte, []int) {
	return file_bucket_proto_rawDescGZIP(), []int{2}
}

func (x *DeleteBucketRequest) GetBucket() string {
	if x != nil {
		return x.Bucket
	}
	return ""
}

type DeleteBucketResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StatusCode    uint32                 `protobuf:"varint,1,opt,name=status_code,json=statusCode,proto3" json:"status_code"`
	StatusMsg     string                 `protobuf:"bytes,2,opt,name=status_msg,json=statusMsg,proto3" json:"status_msg"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteBucketResponse) Reset() {
	*x = DeleteBucketResponse{}
	mi := &file_bucket_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteBucketResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteBucketResponse) ProtoMessage() {}

func (x *DeleteBucketResponse) ProtoReflect() protoreflect.Message {
	mi := &file_bucket_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteBucketResponse.ProtoReflect.Descriptor instead.
func (*DeleteBucketResponse) Descriptor() ([]byte, []int) {
	return file_bucket_proto_rawDescGZIP(), []int{3}
}

func (x *DeleteBucketResponse) GetStatusCode() uint32 {
	if x != nil {
		return x.StatusCode
	}
	return 0
}

func (x *DeleteBucketResponse) GetStatusMsg() string {
	if x != nil {
		return x.StatusMsg
	}
	return ""
}

type ShowBucketRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserName      string                 `protobuf:"bytes,1,opt,name=user_name,json=userName,proto3" json:"user_name"`
	Bucket        string                 `protobuf:"bytes,2,opt,name=bucket,proto3" json:"bucket"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShowBucketRequest) Reset() {
	*x = ShowBucketRequest{}
	mi := &file_bucket_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShowBucketRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShowBucketRequest) ProtoMessage() {}

func (x *ShowBucketRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bucket_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShowBucketRequest.ProtoReflect.Descriptor instead.
func (*ShowBucketRequest) Descriptor() ([]byte, []int) {
	return file_bucket_proto_rawDescGZIP(), []int{4}
}

func (x *ShowBucketRequest) GetUserName() string {
	if x != nil {
		return x.UserName
	}
	return ""
}

func (x *ShowBucketRequest) GetBucket() string {
	if x != nil {
		return x.Bucket
	}
	return ""
}

type ShowBucketResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	StatusCode      uint32                 `protobuf:"varint,1,opt,name=status_code,json=statusCode,proto3" json:"status_code"`
	StatusMsg       string                 `protobuf:"bytes,2,opt,name=status_msg,json=statusMsg,proto3" json:"status_msg"`
	Area            string                 `protobuf:"bytes,3,opt,name=area,proto3" json:"area"` //桶的存储服务器所在地
	StorageType     StorageType            `protobuf:"varint,4,opt,name=storage_type,json=storageType,proto3,enum=rpc.bucket.StorageType" json:"storage_type"`
	AclType         BucketACLType          `protobuf:"varint,5,opt,name=acl_type,json=aclType,proto3,enum=rpc.bucket.BucketACLType" json:"acl_type"`
	CreateTimestamp string                 `protobuf:"bytes,6,opt,name=create_timestamp,json=createTimestamp,proto3" json:"create_timestamp"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ShowBucketResponse) Reset() {
	*x = ShowBucketResponse{}
	mi := &file_bucket_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShowBucketResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShowBucketResponse) ProtoMessage() {}

func (x *ShowBucketResponse) ProtoReflect() protoreflect.Message {
	mi := &file_bucket_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShowBucketResponse.ProtoReflect.Descriptor instead.
func (*ShowBucketResponse) Descriptor() ([]byte, []int) {
	return file_bucket_proto_rawDescGZIP(), []int{5}
}

func (x *ShowBucketResponse) GetStatusCode() uint32 {
	if x != nil {
		return x.StatusCode
	}
	return 0
}

func (x *ShowBucketResponse) GetStatusMsg() string {
	if x != nil {
		return x.StatusMsg
	}
	return ""
}

func (x *ShowBucketResponse) GetArea() string {
	if x != nil {
		return x.Area
	}
	return ""
}

func (x *ShowBucketResponse) GetStorageType() StorageType {
	if x != nil {
		return x.StorageType
	}
	return StorageType_STANDARD
}

func (x *ShowBucketResponse) GetAclType() BucketACLType {
	if x != nil {
		return x.AclType
	}
	return BucketACLType_PRIVATE
}

func (x *ShowBucketResponse) GetCreateTimestamp() string {
	if x != nil {
		return x.CreateTimestamp
	}
	return ""
}

var File_bucket_proto protoreflect.FileDescriptor

const file_bucket_proto_rawDesc = "" +
	"\n" +
	"\fbucket.proto\x12\n" +
	"rpc.bucket\"\xb3\x01\n" +
	"\x13CreateBucketRequest\x12\x16\n" +
	"\x06bucket\x18\x01 \x01(\tR\x06bucket\x12\x12\n" +
	"\x04area\x18\x02 \x01(\tR\x04area\x12:\n" +
	"\fstorage_type\x18\x03 \x01(\x0e2\x17.rpc.bucket.StorageTypeR\vstorageType\x124\n" +
	"\bacl_type\x18\x04 \x01(\x0e2\x19.rpc.bucket.BucketACLTypeR\aaclType\"\x81\x01\n" +
	"\x14CreateBucketResponse\x12\x1f\n" +
	"\vstatus_code\x18\x01 \x01(\rR\n" +
	"statusCode\x12\x1d\n" +
	"\n" +
	"status_msg\x18\x02 \x01(\tR\tstatusMsg\x12)\n" +
	"\x10create_timestamp\x18\x03 \x01(\tR\x0fcreateTimestamp\"-\n" +
	"\x13DeleteBucketRequest\x12\x16\n" +
	"\x06bucket\x18\x01 \x01(\tR\x06bucket\"V\n" +
	"\x14DeleteBucketResponse\x12\x1f\n" +
	"\vstatus_code\x18\x01 \x01(\rR\n" +
	"statusCode\x12\x1d\n" +
	"\n" +
	"status_msg\x18\x02 \x01(\tR\tstatusMsg\"H\n" +
	"\x11ShowBucketRequest\x12\x1b\n" +
	"\tuser_name\x18\x01 \x01(\tR\buserName\x12\x16\n" +
	"\x06bucket\x18\x02 \x01(\tR\x06bucket\"\x85\x02\n" +
	"\x12ShowBucketResponse\x12\x1f\n" +
	"\vstatus_code\x18\x01 \x01(\rR\n" +
	"statusCode\x12\x1d\n" +
	"\n" +
	"status_msg\x18\x02 \x01(\tR\tstatusMsg\x12\x12\n" +
	"\x04area\x18\x03 \x01(\tR\x04area\x12:\n" +
	"\fstorage_type\x18\x04 \x01(\x0e2\x17.rpc.bucket.StorageTypeR\vstorageType\x124\n" +
	"\bacl_type\x18\x05 \x01(\x0e2\x19.rpc.bucket.BucketACLTypeR\aaclType\x12)\n" +
	"\x10create_timestamp\x18\x06 \x01(\tR\x0fcreateTimestamp*)\n" +
	"\vStorageType\x12\f\n" +
	"\bSTANDARD\x10\x00\x12\f\n" +
	"\bLOW_FREQ\x10\x01*9\n" +
	"\rBucketACLType\x12\v\n" +
	"\aPRIVATE\x10\x00\x12\x0f\n" +
	"\vPUBLIC_READ\x10\x01\x12\n" +
	"\n" +
	"\x06PUBLIC\x10\x022\x82\x02\n" +
	"\rBucketService\x12Q\n" +
	"\fCreateBucket\x12\x1f.rpc.bucket.CreateBucketRequest\x1a .rpc.bucket.CreateBucketResponse\x12Q\n" +
	"\fDeleteBucket\x12\x1f.rpc.bucket.DeleteBucketRequest\x1a .rpc.bucket.DeleteBucketResponse\x12K\n" +
	"\n" +
	"ShowBucket\x12\x1d.rpc.bucket.ShowBucketRequest\x1a\x1e.rpc.bucket.ShowBucketResponseB\x1bZ\x19QuickStone/src/rpc/bucketb\x06proto3"

var (
	file_bucket_proto_rawDescOnce sync.Once
	file_bucket_proto_rawDescData []byte
)

func file_bucket_proto_rawDescGZIP() []byte {
	file_bucket_proto_rawDescOnce.Do(func() {
		file_bucket_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_bucket_proto_rawDesc), len(file_bucket_proto_rawDesc)))
	})
	return file_bucket_proto_rawDescData
}

var file_bucket_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_bucket_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_bucket_proto_goTypes = []any{
	(StorageType)(0),             // 0: rpc.bucket.StorageType
	(BucketACLType)(0),           // 1: rpc.bucket.BucketACLType
	(*CreateBucketRequest)(nil),  // 2: rpc.bucket.CreateBucketRequest
	(*CreateBucketResponse)(nil), // 3: rpc.bucket.CreateBucketResponse
	(*DeleteBucketRequest)(nil),  // 4: rpc.bucket.DeleteBucketRequest
	(*DeleteBucketResponse)(nil), // 5: rpc.bucket.DeleteBucketResponse
	(*ShowBucketRequest)(nil),    // 6: rpc.bucket.ShowBucketRequest
	(*ShowBucketResponse)(nil),   // 7: rpc.bucket.ShowBucketResponse
}
var file_bucket_proto_depIdxs = []int32{
	0, // 0: rpc.bucket.CreateBucketRequest.storage_type:type_name -> rpc.bucket.StorageType
	1, // 1: rpc.bucket.CreateBucketRequest.acl_type:type_name -> rpc.bucket.BucketACLType
	0, // 2: rpc.bucket.ShowBucketResponse.storage_type:type_name -> rpc.bucket.StorageType
	1, // 3: rpc.bucket.ShowBucketResponse.acl_type:type_name -> rpc.bucket.BucketACLType
	2, // 4: rpc.bucket.BucketService.CreateBucket:input_type -> rpc.bucket.CreateBucketRequest
	4, // 5: rpc.bucket.BucketService.DeleteBucket:input_type -> rpc.bucket.DeleteBucketRequest
	6, // 6: rpc.bucket.BucketService.ShowBucket:input_type -> rpc.bucket.ShowBucketRequest
	3, // 7: rpc.bucket.BucketService.CreateBucket:output_type -> rpc.bucket.CreateBucketResponse
	5, // 8: rpc.bucket.BucketService.DeleteBucket:output_type -> rpc.bucket.DeleteBucketResponse
	7, // 9: rpc.bucket.BucketService.ShowBucket:output_type -> rpc.bucket.ShowBucketResponse
	7, // [7:10] is the sub-list for method output_type
	4, // [4:7] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_bucket_proto_init() }
func file_bucket_proto_init() {
	if File_bucket_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_bucket_proto_rawDesc), len(file_bucket_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_bucket_proto_goTypes,
		DependencyIndexes: file_bucket_proto_depIdxs,
		EnumInfos:         file_bucket_proto_enumTypes,
		MessageInfos:      file_bucket_proto_msgTypes,
	}.Build()
	File_bucket_proto = out.File
	file_bucket_proto_goTypes = nil
	file_bucket_proto_depIdxs = nil
}
