// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v5.29.3
// source: transmission.proto

package transmission

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UploadObjectRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"` // 定位到要将对象上传到哪个用户的存储资源下
	Bucket        string                 `protobuf:"bytes,2,opt,name=bucket,proto3" json:"bucket,omitempty"`
	Key           string                 `protobuf:"bytes,3,opt,name=key,proto3" json:"key,omitempty"`
	ObjectType    string                 `protobuf:"bytes,4,opt,name=object_type,json=objectType,proto3" json:"object_type,omitempty"`
	FileData      []byte                 `protobuf:"bytes,5,opt,name=file_data,json=fileData,proto3" json:"file_data,omitempty"`
	Token         string                 `protobuf:"bytes,6,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadObjectRequest) Reset() {
	*x = UploadObjectRequest{}
	mi := &file_transmission_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadObjectRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadObjectRequest) ProtoMessage() {}

func (x *UploadObjectRequest) ProtoReflect() protoreflect.Message {
	mi := &file_transmission_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadObjectRequest.ProtoReflect.Descriptor instead.
func (*UploadObjectRequest) Descriptor() ([]byte, []int) {
	return file_transmission_proto_rawDescGZIP(), []int{0}
}

func (x *UploadObjectRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UploadObjectRequest) GetBucket() string {
	if x != nil {
		return x.Bucket
	}
	return ""
}

func (x *UploadObjectRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *UploadObjectRequest) GetObjectType() string {
	if x != nil {
		return x.ObjectType
	}
	return ""
}

func (x *UploadObjectRequest) GetFileData() []byte {
	if x != nil {
		return x.FileData
	}
	return nil
}

func (x *UploadObjectRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type UploadObjectResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StatusCode    uint32                 `protobuf:"varint,1,opt,name=status_code,json=statusCode,proto3" json:"status_code,omitempty"`
	StatusMsg     string                 `protobuf:"bytes,2,opt,name=status_msg,json=statusMsg,proto3" json:"status_msg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadObjectResponse) Reset() {
	*x = UploadObjectResponse{}
	mi := &file_transmission_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadObjectResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadObjectResponse) ProtoMessage() {}

func (x *UploadObjectResponse) ProtoReflect() protoreflect.Message {
	mi := &file_transmission_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadObjectResponse.ProtoReflect.Descriptor instead.
func (*UploadObjectResponse) Descriptor() ([]byte, []int) {
	return file_transmission_proto_rawDescGZIP(), []int{1}
}

func (x *UploadObjectResponse) GetStatusCode() uint32 {
	if x != nil {
		return x.StatusCode
	}
	return 0
}

func (x *UploadObjectResponse) GetStatusMsg() string {
	if x != nil {
		return x.StatusMsg
	}
	return ""
}

type DownloadObjectRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint64                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Bucket        string                 `protobuf:"bytes,2,opt,name=bucket,proto3" json:"bucket,omitempty"`
	Key           string                 `protobuf:"bytes,3,opt,name=key,proto3" json:"key,omitempty"`
	Token         string                 `protobuf:"bytes,4,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DownloadObjectRequest) Reset() {
	*x = DownloadObjectRequest{}
	mi := &file_transmission_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DownloadObjectRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DownloadObjectRequest) ProtoMessage() {}

func (x *DownloadObjectRequest) ProtoReflect() protoreflect.Message {
	mi := &file_transmission_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DownloadObjectRequest.ProtoReflect.Descriptor instead.
func (*DownloadObjectRequest) Descriptor() ([]byte, []int) {
	return file_transmission_proto_rawDescGZIP(), []int{2}
}

func (x *DownloadObjectRequest) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *DownloadObjectRequest) GetBucket() string {
	if x != nil {
		return x.Bucket
	}
	return ""
}

func (x *DownloadObjectRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *DownloadObjectRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type DownloadObjectResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StatusCode    uint32                 `protobuf:"varint,1,opt,name=status_code,json=statusCode,proto3" json:"status_code,omitempty"`
	StatusMsg     string                 `protobuf:"bytes,2,opt,name=status_msg,json=statusMsg,proto3" json:"status_msg,omitempty"`
	Object        []byte                 `protobuf:"bytes,3,opt,name=object,proto3" json:"object,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DownloadObjectResponse) Reset() {
	*x = DownloadObjectResponse{}
	mi := &file_transmission_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DownloadObjectResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DownloadObjectResponse) ProtoMessage() {}

func (x *DownloadObjectResponse) ProtoReflect() protoreflect.Message {
	mi := &file_transmission_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DownloadObjectResponse.ProtoReflect.Descriptor instead.
func (*DownloadObjectResponse) Descriptor() ([]byte, []int) {
	return file_transmission_proto_rawDescGZIP(), []int{3}
}

func (x *DownloadObjectResponse) GetStatusCode() uint32 {
	if x != nil {
		return x.StatusCode
	}
	return 0
}

func (x *DownloadObjectResponse) GetStatusMsg() string {
	if x != nil {
		return x.StatusMsg
	}
	return ""
}

func (x *DownloadObjectResponse) GetObject() []byte {
	if x != nil {
		return x.Object
	}
	return nil
}

var File_transmission_proto protoreflect.FileDescriptor

const file_transmission_proto_rawDesc = "" +
	"\n" +
	"\x12transmission.proto\x12\x10rpc.transmission\"\xac\x01\n" +
	"\x13UploadObjectRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x16\n" +
	"\x06bucket\x18\x02 \x01(\tR\x06bucket\x12\x10\n" +
	"\x03key\x18\x03 \x01(\tR\x03key\x12\x1f\n" +
	"\vobject_type\x18\x04 \x01(\tR\n" +
	"objectType\x12\x1b\n" +
	"\tfile_data\x18\x05 \x01(\fR\bfileData\x12\x14\n" +
	"\x05token\x18\x06 \x01(\tR\x05token\"V\n" +
	"\x14UploadObjectResponse\x12\x1f\n" +
	"\vstatus_code\x18\x01 \x01(\rR\n" +
	"statusCode\x12\x1d\n" +
	"\n" +
	"status_msg\x18\x02 \x01(\tR\tstatusMsg\"p\n" +
	"\x15DownloadObjectRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x04R\x06userId\x12\x16\n" +
	"\x06bucket\x18\x02 \x01(\tR\x06bucket\x12\x10\n" +
	"\x03key\x18\x03 \x01(\tR\x03key\x12\x14\n" +
	"\x05token\x18\x04 \x01(\tR\x05token\"p\n" +
	"\x16DownloadObjectResponse\x12\x1f\n" +
	"\vstatus_code\x18\x01 \x01(\rR\n" +
	"statusCode\x12\x1d\n" +
	"\n" +
	"status_msg\x18\x02 \x01(\tR\tstatusMsg\x12\x16\n" +
	"\x06object\x18\x03 \x01(\fR\x06object2\xd9\x01\n" +
	"\x13TransmissionService\x12]\n" +
	"\fUploadObject\x12%.rpc.transmission.UploadObjectRequest\x1a&.rpc.transmission.UploadObjectResponse\x12c\n" +
	"\x0eDownloadObject\x12'.rpc.transmission.DownloadObjectRequest\x1a(.rpc.transmission.DownloadObjectResponseB!Z\x1fQuickStone/src/rpc/transmissionb\x06proto3"

var (
	file_transmission_proto_rawDescOnce sync.Once
	file_transmission_proto_rawDescData []byte
)

func file_transmission_proto_rawDescGZIP() []byte {
	file_transmission_proto_rawDescOnce.Do(func() {
		file_transmission_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_transmission_proto_rawDesc), len(file_transmission_proto_rawDesc)))
	})
	return file_transmission_proto_rawDescData
}

var file_transmission_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_transmission_proto_goTypes = []any{
	(*UploadObjectRequest)(nil),    // 0: rpc.transmission.UploadObjectRequest
	(*UploadObjectResponse)(nil),   // 1: rpc.transmission.UploadObjectResponse
	(*DownloadObjectRequest)(nil),  // 2: rpc.transmission.DownloadObjectRequest
	(*DownloadObjectResponse)(nil), // 3: rpc.transmission.DownloadObjectResponse
}
var file_transmission_proto_depIdxs = []int32{
	0, // 0: rpc.transmission.TransmissionService.UploadObject:input_type -> rpc.transmission.UploadObjectRequest
	2, // 1: rpc.transmission.TransmissionService.DownloadObject:input_type -> rpc.transmission.DownloadObjectRequest
	1, // 2: rpc.transmission.TransmissionService.UploadObject:output_type -> rpc.transmission.UploadObjectResponse
	3, // 3: rpc.transmission.TransmissionService.DownloadObject:output_type -> rpc.transmission.DownloadObjectResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_transmission_proto_init() }
func file_transmission_proto_init() {
	if File_transmission_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_transmission_proto_rawDesc), len(file_transmission_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_transmission_proto_goTypes,
		DependencyIndexes: file_transmission_proto_depIdxs,
		MessageInfos:      file_transmission_proto_msgTypes,
	}.Build()
	File_transmission_proto = out.File
	file_transmission_proto_goTypes = nil
	file_transmission_proto_depIdxs = nil
}
